name: auto-merge

on:
  pull_request:
  workflow_dispatch:

jobs:
  auto-merge:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: fastify/github-action-merge-dependabot@v3.3.0
